"use client"
import Link from "next/link";
import { useRouter } from "next/navigation";
import "./globals.css";

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({children}:{children: React.ReactNode}) {

	// linked
  const router = useRouter()
  const dataClick=(url:any)=>{
    router.push(url)
  }
	// component
	const menuItems=(url:string, label:string, className?:string)=>(
	<div className= {`bg-black text-white py-2 px-3 rounded-lg ${className}`}>
		<Link href={url}><p>{label}</p></Link>
	</div>
	)

	return (
		<html lang="en">
			<head>
				<title>hahah</title>
			</head>
			<body className="container mx-auto py-[10px]">
				<>
					<div className="flex flex-row space-x-3 w-full">
						{menuItems("/","Home","bg-white text-blue-500 text-lg")}
						<div className="flex flex-row items-end space-x-3 justify-end w-full">
						{menuItems("/","Home")}
						{menuItems("/dashboard","dashboard")}
						{menuItems("/calculator","calculator")}
						{menuItems("/setting","setting")}
						{menuItems("/cari","cari")}
			
						{/* <li style={{cursor:'pointer'}} onClick={() => dataClick("/setting")}>Setting</li> */}
				
					</div>
					</div>
				
					{children}
				</>
			</body>
		</html>
	);
}
