import NavbarComponent from '@/components/NavbarComponent'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <NavbarComponent/>
        {children}
      </body>
    </html>
  )
}
