import NavbarComponent from "@/components/NavbarComponent";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin=""
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Cookie&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body>
				<NavbarComponent />
				{children}
			</body>
		</html>
	);
}
